spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret-key: zxcvzxcvzxcvzxcvzxcvzxcvzxcvzxcv
    access-expiration-time: 3600000 #1시간
    refresh-expiration-time: 1210000000 #2주