server:
  port: 8889

spring:
  config:
    import:
      - classpath:application-secret.yml
  datasource:
    url: jdbc:mysql://localhost:3306/gourmet_re
    username: gourmetRe
    password: gourmetRe
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
